# -*- coding: utf-8 -*-
"""pp_laboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oDoNbuCH70F1Oc4hExcBx5GF61gsOVPx
"""

#3
a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
print("sum is ",a+b)
print("difference is ",a-b)
print("product is",a*b)
print("division is ",a/b)
print("mod is ",a%b)

#4 i
import math
p=int(input("enter the principal amount:"))
r=int(input("enter the rate of interest:"))
t=int(input("enter the time period:"))
ci=p*math.pow((1+r/100),t)
print(ci)

#4 ii
import math
p1=[4,0]
p2=[6,6]
distance=math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
print(distance)

#5
n=str(input("enter the name:"))
m=str(input("enter the address:"))
o=str(input("enter the email:"))
p=int(input("enter the phone number:"))
print(n)
print(m)
print(o)
print(p)

#6
import math
r=int(input("enter the radius of the circle:"))
area=math.pi*r*r
print("area of circle is {}".format(area))

#8
import math
a=int(input("enter the value of a:"))
b=int(input("enter the value of b:"))
c=int(input("enter the value of c:"))
s=(a+b+c)/2
area=math.sqrt(s*(s-a)*(s-b)*(s-c))
print("area fo triangle is {}".format(area))

#9
a,b,c,d,e=[int(a) for a in input("enter the marks of the subjects:").split()]
average=(a+b+c+d+e)/5
print("average of marks is {}".format(average))                                        #method1

#method2
a,b,c,d,e=list(map(int,input("enter the marks of of 5 students:").split()))
average=(a+b+c+d+e)/5
print("average of marks is {}".format(average))

#10 i,ii
a=int(input("enter the value of a:"))
b=int(input("enter the value of b:"))
temp=a
a=b
b=temp
print("the value of a after swapping is:",a)
print("the value of b after swapping is:",b)
c=int(input("enter the value of c:"))
d=int(input("enter the value of d:"))
c=c+d
d=c-d
c=c-d
print("the value of c after swapping is:",c)
print("the value of d after swapping is:",d)
e=int(input("enter the value of e:"))
f=int(input("enter the value of f:"))
e,f=f,e
print(e)
print(f)

#11
a=int(input("ente the value of a:"))
b=int(input("enter the value of b:"))
c=int(input("enter the value of c:"))
d=int(input("enter the value of d:"))
print("a is {}\n b is {}\n c is {}\n d is {}".format(a,b,c,d))

"""Programming Exercises on Conditional Statements,loops"""

#1
rows=int(input("enter the number of rows:"))
for i in range(0,rows):
  for j in range(0,i+1):
    print(rows,end="")
  rows=rows-1
  print("\n")

#2
ch=input("enter a character:")
if ch>='a' and ch<='z':
  print("{} is a lowercase character".format(ch))
elif ch>='A' and ch<='Z':
  print("{} is a uppercase character".format(ch))
elif ch>=0 and ch<=9:
  print("{} is a digit".format(ch))
else:
  print("{} is special character".format(ch))

#3
n=int(input("Enter the value of 'n:"))
a=0
b=1
sum=0
count=1
print("Fibonacci series : ",end =" ")
while(count <=n):
  print(sum, end =" ")
  count +=1
  a=b
  b=sum
  sum= a+b

#4
lower_value=int(input("enter the lowest range value:"))
higher_value=int(input("enter the highest range value:"))
print("The Prime numbers in the range are:")
for number in range(lower_value,higher_value+1):
  if number>1:
    for i in range(2,number):
      if number%i==0:
        break
    else:
      print(number)

#5
num = float(input("Enter a number: "))
if num > 0:
   print("Positive number")
elif num == 0:
   print("Zero")
else:
   print("Negative number")

#6
r=range(2,20)
n=int(input("enter a number:"))
if n in r:
  print("the number you have entered is in the range")
else:
   print("the number you have entered is not in the range")

#7
#Largest of three numbers
var3=lambda x,y,z: [x if x>y and x>z else y if y>z else z]
var3(90,34,76)

#7 method 2
x,y,z=[int(z) for z in input("enter three numbers:").split()]
if x>y and x>z:
  print(x,"is largest")
elif y>x and y>z:
  print(y,"is largest")  
else:
  print(z,"is largest")

#8
for num in range(1,6):
  if(num%3==0 and num%5==0):
    print("FizzBuzz")
  elif(num%3 == 0):
    print("Fizz")
  elif(num%5 == 0):
    print("Buzz")
  else:
    print(num)

#9
percentage=float(input("enter the percentage:"))
if percentage<=100 and percentage>=90:
  print("A+")
elif percentage>90 and percentage>=75:
  print("A")
elif percentage>75 and percentage>=65:  
  print("B+")
elif percentage>65 and percentage>=55: 
  print("B")
elif percentage>55 and percentage>=40:
  print("C")   
else:
  print("Student is failed")

#10
for i in range(1,21):
  print(i**2)

#11
num = input("Enter Number: ")
sum = 0
for i in num:
    sum = sum + int(i)
print(sum)

#12
num=int(input("Enter a number:"))
temp=num
rev=0
while(num>0):
    sum=num%10
    rev=rev*10+sum
    num=num//10
if(temp==rev):
    print("The number is a palindrome")
else:
    print("The number is not a palindrome")

"""Additional Exercises"""

#1
import random
a=int(input("enter a number")) 
b= random.randint(1, 10)
while a!= b:
    b= int(input('Guess a number between 1 to 10 '))
print('Well guessed')

#2
num=10
print(type(num))
print(id(num))
del num
print(num)

#3
def get_permutation(string, i=0):
    if i == len(string):   	 
        print("".join(string))
    for j in range(i, len(string)):
        words = [c for c in string]
        words[i], words[j] = words[j], words[i]  	 
        get_permutation(words, i + 1)
print(get_permutation('CAT'))

#4
import calendar
y = int(input("enter the year : "))
m = int(input("enter the month : "))
print(calendar.month(y, m))